### ISSUE TITLE
No support for ToXMLContentHandler

### ISSUE THREAD

**Issue by aleksandrskrivickis** [databrickslabs/tika-ocr#45]
Current [handler](https://github.com/databrickslabs/tika-ocr/blob/fbf1976911eb4aebf9c95bff4c17517cfd2c6318/src/main/scala/com/databricks/labs/tika/TikaExtractor.scala#L30) returns plain text. Tika allows more structured output in form of `XML` using [ToXMLContentHandler](https://tika.apache.org/1.18/api/org/apache/tika/sax/ToXMLContentHandler.html). 

I propose to introduce optional parameter that would allow XML output if necessary to obtain more strucutred data.

**Comment by arcaputo3** [comment]
Feel free to give this a shot: https://github.com/TJC-LP/tika-ocr/tree/TJC-LP/enable-xml-output

I'm going to test it in our Databricks workspace in the next few days, but locally seems to work as expected.
